version: '3'
services:
  eureka-server:
    image: employee-management-eureka-server:1.0
    container_name: eureka-server
    expose:
    - "8761"
    ports: 
    - 8761:8761 
  employee-service:
    image: employee-microservice:1.0
    #container_name: employee-microservice
    ports:
    - "8280"
    environment:
      - JAVA_OPTS=
            -DEUREKA_SERVER=http://eureka-server:8761/eureka -DDB_USER=admin -DDB_PASSWORD=welcome1 -DJDBC_URL=jdbc:mariadb://training.calpumbnnhqy.us-east-1.rds.amazonaws.com:3306/training
      
    links: 
        - eureka-server
        
  admin-service:
    image: admin-microservice:1.0
    #container_name: admin-microservice
    ports:
    - "8180"
    environment:
      - JAVA_OPTS=
            -DEUREKA_SERVER=http://eureka-server:8761/eureka
      
    links: 
        - eureka-server
 
        
  gateway-service:
    image: employee-managment-gateway:1.0
    #container_name: gateway-service
    ports:
    - "8000:8000"
    environment:
      - JAVA_OPTS=
            -DEUREKA_SERVER=http://eureka-server:8761/eureka  #(name of eureka host==eureka container name)
      
    links: 
        - eureka-server
 